version: '3.8'

services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database
    secrets:
      - db_password

secrets:
  db_password:
    file: $SECRET_FILE_PATH

volumes:
  postgres_data:
